### ISSUE TITLE
Missing File fer2013.csv

### ISSUE THREAD

**Issue by kaliaabhishek** [Deep911/webCamEmocognizer#1]
Hi!

I've been trying to work around with your awesome project but I am unable to generate scaled images because the fer2013.csv does not exist.
I tried downloading it from the kaggle website but because I am from India, I am unable to receive the confirmation sms required to validate the download.
Is it possible to get that file from somewhere else?

Thanks.

**Comment by deepcode-debug** [comment]
Alrite, u can download it from here: https://drive.google.com/file/d/1ypZVVjz39kB20TZcTTUkf4wU33UTQIqJ/view?usp=sharing

**Comment by kaliaabhishek** [comment]
Thanks!
